fix TimeJobs duetime too big
PomeloFoundation/dotNETCore-Extensions pull request #16
Opened 2017-07-29 13:02 UTC by liguobao

https://github.com/PomeloFoundation/dotNETCore-Extensions/issues/13

2017-07-29 13:04 UTC, yukozh requested changes

2017-07-29 13:04 UTC, Kagamine commented on src/Pomelo.AspNetCore.TimedJob/TimedJobService.cs
> +                            long delta = 0;
ulong

2017-07-29 13:04 UTC, Kagamine commented on src/Pomelo.AspNetCore.TimedJob/TimedJobService.cs
> +                                delta = Convert.ToInt64((invoke._begin - DateTime.Now).TotalMilliseconds);
UInt64

2017-07-29 13:04 UTC, Kagamine commented on src/Pomelo.AspNetCore.TimedJob/TimedJobService.cs
> +                            if(delta > Int32.MaxValue)
same as before

2017-07-29 13:17 UTC, yukozh requested changes

2017-07-29 13:17 UTC, Kagamine commented on src/Pomelo.AspNetCore.TimedJob/TimedJobService.cs
> +                    delta = delta % (uint)x.Interval;
Could you use Convert.ToUInt64 instead of explict conversion?

2017-07-29 13:20 UTC, liguobao commented on src/Pomelo.AspNetCore.TimedJob/TimedJobService.cs
> +                    delta = delta % (uint)x.Interval;
ok,I know.

2017-07-30 00:08 UTC, yukozh approved these changes

2017-08-05 10:23 UTC, merged